// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC_BuyNET.Data;

#nullable disable

namespace PC_BuyNET.Migrations
{
    [DbContext(typeof(PC_BuyNETDbContext))]
    [Migration("20250612183127_InitialMigration1")]
    partial class InitialMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PC_BuyNET.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop for gaming.",
                            Name = "Gaming Laptop",
                            Type = "Laptop",
                            price = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "RGB backlit mechanical keyboard.",
                            Name = "Mechanical Keyboard",
                            Type = "Keyboard",
                            price = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ergonomic gaming mouse with customizable buttons.",
                            Name = "Gaming Mouse",
                            Type = "Mouse",
                            price = 80.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
